/** Persian strings for the booking page (kept out of JSX-heavy files). */
export const B = {
  bookTab: 'رزرو نوبت',
  manageTab: 'مدیریت نوبت من',
  clinicName: 'درمانگاه شبانه‌روزی طب الرضا(ع)',
  wizardTitle: 'رزرو نوبت درمانگاه طب الرضا(ع)',
  stepDoctor: 'پزشک',
  stepDay: 'روز',
  stepTime: 'ساعت',
  stepInfo: 'اطلاعات',
  chooseDoctor: 'انتخاب پزشک',
  chooseDay: 'انتخاب روز کاری (دو هفته آینده)',
  chooseTime: 'انتخاب ساعت آزاد',
  noWorkingDays: 'این پزشک در دو هفته آینده روز کاری ندارد.',
  noFreeTime: 'برای این روز ساعت آزادی پیدا نشد.',
  patientName: 'نام و نام خانوادگی',
  patientPhone: 'شماره موبایل',
  notes: 'توضیحات (اختیاری)',
  submit: 'ثبت نوبت',
  doneTitle: 'نوبت شما ثبت شد!',
  doneSub: 'پیامک تایید برای شما ارسال می‌شود.',
  trackingCode: 'کد پیگیری',
  newBooking: 'ثبت نوبت جدید',
  codeLabel: 'کد پیگیری',
  phoneLabel: 'موبایل',
  lookup: 'جستجو',
  cancelRequest: 'دریافت کد لغو',
  otpSent: 'کد پیامک شد',
  otpLabel: 'کد دریافتی',
  confirmCancel: 'لغو نوبت',
  cancelled: 'نوبت شما لغو شد.',
  manageAgain: 'بازگشت به جستجو',
  statusActive: 'فعال',
  enterOtpHint: 'کد ۶ رقمی پیامک‌شده را وارد کنید:',
  back: 'بازگشت',
}
